### PR TITLE
Add roshambo demo on EMG

### PR DESCRIPTION
**Pull request by bertrandlalo**

### CODE REVIEW

**Comment by mesca** [comment]
Some notes:

- [ ] Add a random data source so one can run the pipeline without hardware nor replay
- [ ] Add a README.md (explain how to use the replay)
- [ ] Save data in the current data dir 
- [ ] Use a generic EMG stream name instead of `bitalino` so the device can easily be replaced, do the channel selection in the `bitalino.yaml` graph
- [ ] Remove the unit converter node (now native in the bitalino plugin)
- [ ] Image credit for the UI?
- [ ] Rename `emg_gesture` to `roshambo` (both in UI and directory)
- [ ] Rework the UI to make it more appealing, auto-detect when the model is ready
- [ ] Take care of this warning: `/Users/mesca/opt/miniconda3/envs/timeflux/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. 'skew', 'kurtosis'), the default behavior of 'mode' typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of 'keepdims' will become False, the 'axis' over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set 'keepdims' to True or False to avoid this warning.`
- [ ] Loop through all numbered ports in the `MovingAverage` node
- [ ] Remove unused code and comments in the JavaScript code
- [ ] `MovingAverage`: remove the `closed` parameter to keep the code simple (`right` as default)
- [ ] Remove old dataset
- [ ] Set or remove `emg_energy`

**Comment by bertrandlalo** [comment]
- [x] Add a random data source so one can run the pipeline without hardware nor replay
 - [x]  Add a README.md (explain how to use the replay)
  - [x] Save data in the current data dir
  - [x] Use a generic EMG stream name instead of bitalino so the device can easily be replaced, do the channel selection in the bitalino.yaml graph
  - [x] Remove the unit converter node (now native in the bitalino plugin)
  - [ ] Image credit for the UI?
  - [x] Rename emg_gesture to roshambo (both in UI and directory)
  - [ ] Rework the UI to make it more appealing, auto-detect when the model is ready
  - [x] Take care of this warning: /Users/mesca/opt/miniconda3/envs/timeflux/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. 'skew', 'kurtosis'), the default behavior of 'mode' typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of 'keepdims' will become False, the 'axis' over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set 'keepdims' to True or False to avoid this warning.
  - [x] Loop through all numbered ports in the MovingAverage node
  - [x] Remove unused code and comments in the JavaScript code
  - [x] MovingAverage: remove the closed parameter to keep the code simple (right as default)
  - [x] Remove old dataset
  - [x] Set or remove emg_energy

**Comment by bertrandlalo** [comment]
> Take care of this warning: /Users/mesca/opt/miniconda3/envs/timeflux/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. 'skew', 'kurtosis'), the default behavior of 'mode' typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of 'keepdims' will become False, the 'axis' over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set 'keepdims' to True or False to avoid this warning.

C'est à l'intérieur de Sklearn.

**Comment by mesca** [comment]
Merged as is, will improve UI later.

**Pull request merged**
